sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20050715.gao

  alioss :
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out-phage
    access-key-id: LTAI5tHDHaYaPhKBJLAwBMxZ
    access-key-secret: bNGJuk37ygDBVg3tyikvlkkIalIczM

  redis:
    host: localhost
    port: 6379
    password:
    database: 0

  wechat:
      appid: wxdba9217578181bed
      secret: b58ae376e9aa0907ecae2cc865170246



